#!/bin/bash
#  ██                     ██                ██    ██           ████   ██  
# ░██                    ░██               ░██   ░██          ░██░   ░██  
# ░██       █████  ██████░██       ██████ ██████ ░██ ██   ██ ██████ ██████
# ░██████  ██░░░██░░██░░█░██████  ██░░░░ ░░░██░  ░██░██  ░██░░░██░ ░░░██░ 
# ░██░░░██░███████ ░██ ░ ░██░░░██░░█████   ░██   ░██░██  ░██  ░██    ░██  
# ░██  ░██░██░░░░  ░██   ░██  ░██ ░░░░░██  ░██   ░██░██  ░██  ░██    ░██  
# ░██  ░██░░██████░███   ░██████  ██████   ░░██  ███░░██████  ░██    ░░██ 
# ░░   ░░  ░░░░░░ ░░░    ░░░░░   ░░░░░░     ░░  ░░░  ░░░░░░   ░░      ░░  
#
# Shinryuu's herbstluftwm
# configuration.

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use alt as the main modifier

#herbstclient load ${TAG_NAMES[0]} '(clients max:0)'

# tags
TAG_NAMES=("term" "web" "img" "null" "herb" "foo")
TAG_KEYS=( {1..6} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Control-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# theme
#hc attr theme.tiling.reset 1
#hc attr theme.floating.reset 1
hc set frame_border_active_color '#161616'
hc set frame_border_normal_color '#161616'
hc set frame_bg_normal_color '#262626'
hc set frame_bg_active_color '#6c3b41'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#5e3838'
hc attr theme.normal.color '#252525'
hc attr theme.urgent.color orange
hc attr theme.inner_width 2
hc attr theme.outer_width 2
hc attr theme.inner_color '#202020'
hc attr theme.border_width 6
hc attr theme.floating.border_width 6
hc attr theme.floating.outer_width 2
hc attr theme.floating.inner_width 2
hc attr theme.floating.inner_color '#282828'
hc attr theme.floating.outer_color '#303030'
hc attr theme.active.inner_color '#282828'
hc attr theme.active.outer_color '#282828'
hc attr theme.normal.inner_color '#303030'
hc attr theme.normal.outer_color '#303030'
hc attr theme.background_color '#ffffff'

# mouse bindings    
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# layouts

hc load term '
(split horizontal:0.500000:0
      (clients vertical:0 0x1400003)
   (split vertical:0.580000:1
      (clients vertical:0)
      (clients vertical:0 0x2a00001)))'

hc load web '
(split horizontal:0.500000:1
   (split vertical:0.500000:1
      (clients vertical:0) 
      (clients vertical:0)) 
   (split vertical:0.500000:0
      (clients vertical:0 0x1a00003)
      (clients vertical:0)))'

# rules
hc unrule -F

# focus new clients
hc rule focus=on

# rules
hc rule class=qutebrowser tag=term focus=on
hc rule class=gimp tag=img focus=on
hc rule class=mpv tag=term focus=on
hc rule class=sxiv tag=term focus=on
hc rule class=wine tag=term focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
hc set_monitors 1920x1080+1280+0 1280x1024+0+0

# panel
#panel.sh &
