#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1    # Use alt as the main modifier

#herbstclient load ${TAG_NAMES[0]} '(clients max:0)'

# tags
TAG_NAMES=( term web img herb null foo )
TAG_KEYS=( {1..6} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Control-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# colors
hc set frame_border_active_color '#1f2124'
hc set frame_border_normal_color '#1c1e21'
hc set frame_bg_active_color '#303033'
hc set frame_bg_normal_color '#1c1e21'
hc set window_border_active_color '#303033'
hc set window_border_normal_color '#1c1e21'
hc set window_border_urgent_color '#4cdcd4'
hc set frame_border_width 2

# behavior
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set window_border_width 4
hc set window_border_inner_width 0
hc set always_show_frame 0
hc set frame_gap 0
hc set frame_bg_transparent 1

# mouse bindings    
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# layouts
hc load term '
(split horizontal:0.500000:0 
     (clients vertical:0 0x1000003)
     (clients vertical:0))'
     
hc load web '
(split horizontal:0.500000:1
     (split vertical:0.500000:1
     (clients vertical:0) 
     (clients vertical:0)) 
(split vertical:0.500000:0
     (clients vertical:0 0x1a00003)
     (clients vertical:0)))'

# rules
hc unrule -F

# focus new clients
hc rule focus=on

# rules for clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

hc rule class=Dwb tag=term focus=on
hc rule class=qutebrowser tag=term focus=on
hc rule class=Chromium tag=term focus=on
hc rule class=mpv tag=term focus=on
hc rule class=sxiv tag=term focus=on
hc rule class=wine tag=term focus=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1920x1080+1280+0
hc detect_monitors

panel.sh &
