#!/bin/bash
# popup calendar for dzen
font="-Gohu-GohuFont-Medium-R-Normal--11-80-100-100-C-60-ISO10646-1"
TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal -m | wc -l)
LINES=$((LINES + 2))

(
date +'^bg(#1c1e21) '
date +''
# current month, highlight header and today
cal -m | sed -r -e "1,2 s/.*/^fg(#d3d3d3)&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg(#3c5a5d)^fg(#94a1b3)\2^fg()^bg()\3/") | dzen2 -x 3100 -y 16 -w 146 -h 12 -l $LINES -sa c -p -e 'onstart=uncollapse,hide;button1=exit;' -fg "#d3d3d3" -bg "#1c1e21" -tw 6 -fn "$font"
)
