#!/bin/bash
# dmenu wrapper, assing some options
# if they weren't given.

main() {
   local ARGS=
   local FONT=
   [[ "$@" != *-fn ]] && FONT="berry 9"
   [[ "$@" != *-nb ]] && ARGS="$ARGS -nb #1d1f22"
   [[ "$@" != *-nf ]] && ARGS="$ARGS -nf #839496"
   [[ "$@" != *-sb ]] && ARGS="$ARGS -sb #202225"
   [[ "$@" != *-sf ]] && ARGS="$ARGS -sf #6e464b"
   [[ -n "$FONT" ]] && {
      /usr/bin/dmenu -fn "$FONT" $ARGS "$@"; return;
   } || { /usr/bin/dmenu $ARGS "$@"; return; }
}
main "$@"
