#!/bin/sh

# settings
bspc config border_width	4
bspc config window_gap	        0
bspc config top_padding		0

bspc monitor DVI-I-2 -d • • •
bspc monitor DVI-I-1 -d • • •

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	false
bspc config auto_alternate		true
bspc config auto_cancel			true
bspc config normal_frame_opacity	0.0
bspc config focused_frame_opacity	0.0

# colors
bspc config normal_border_color		"#1f1f22"
bspc config active_border_color		"#292929"
bspc config focused_border_color	"#323232"
bspc config presel_border_color		"#9a875f"
bspc config urgent_border_color		"#9f7155"
bspc config focused_locked_border_color "#9a875f"

# Rules
bspc rule -a mpv desktop=^1 follow=on floating=on
bspc rule -a sxiv desktop=^1 follow=on floating=on